name: Deploy the API
on:
  # Triggers the workflow on push event on master
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Connect to the UCM container using SHH, push the changes of the repository and restart the API service
      - name: API deployment
        uses: appleboy/ssh-action@master #garygrossgarten/github-action-ssh@release
        with:
          command: ls -a
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            ls
            cd TFG/TFG-2021-Pict2Text2.0
            git pull
            cd API
            export HISTIGNORE="*sudo -S*"
            echo ${{ secrets.SSH_USER }} | sudo -S -k systemctl restart pict2text2.service
            systemctl status pict2text2.service
            echo "Pipeline finished"
